package com.unbank.mybatis.entity;

public class EmailReiver {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reiver_email.id
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reiver_email.name
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reiver_email.host
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private String host;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reiver_email.rank
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private Byte rank;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reiver_email.id
	 * @return  the value of reiver_email.id
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reiver_email.id
	 * @param id  the value for reiver_email.id
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reiver_email.name
	 * @return  the value of reiver_email.name
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reiver_email.name
	 * @param name  the value for reiver_email.name
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reiver_email.host
	 * @return  the value of reiver_email.host
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public String getHost() {
		return host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reiver_email.host
	 * @param host  the value for reiver_email.host
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setHost(String host) {
		this.host = host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reiver_email.rank
	 * @return  the value of reiver_email.rank
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public Byte getRank() {
		return rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reiver_email.rank
	 * @param rank  the value for reiver_email.rank
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setRank(Byte rank) {
		this.rank = rank;
	}
}