package com.unbank.mybatis.entity;

public class EmailSender {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sender_email.id
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sender_email.name
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sender_email.password
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sender_email.host
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private String host;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sender_email.rank
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private Integer rank;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sender_email.id
	 * @return  the value of sender_email.id
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sender_email.id
	 * @param id  the value for sender_email.id
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sender_email.name
	 * @return  the value of sender_email.name
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sender_email.name
	 * @param name  the value for sender_email.name
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sender_email.password
	 * @return  the value of sender_email.password
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sender_email.password
	 * @param password  the value for sender_email.password
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sender_email.host
	 * @return  the value of sender_email.host
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public String getHost() {
		return host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sender_email.host
	 * @param host  the value for sender_email.host
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setHost(String host) {
		this.host = host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sender_email.rank
	 * @return  the value of sender_email.rank
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public Integer getRank() {
		return rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sender_email.rank
	 * @param rank  the value for sender_email.rank
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setRank(Integer rank) {
		this.rank = rank;
	}
}