package com.unbank.mybatis.entity;

public class EmailInfoWithBLOBs extends EmailInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column email_info.content
	 * @mbggenerated  Mon Feb 27 09:16:07 GMT+08:00 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column email_info.file
	 * @mbggenerated  Mon Feb 27 09:16:07 GMT+08:00 2017
	 */
	private String file;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column email_info.content
	 * @return  the value of email_info.content
	 * @mbggenerated  Mon Feb 27 09:16:07 GMT+08:00 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column email_info.content
	 * @param content  the value for email_info.content
	 * @mbggenerated  Mon Feb 27 09:16:07 GMT+08:00 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column email_info.file
	 * @return  the value of email_info.file
	 * @mbggenerated  Mon Feb 27 09:16:07 GMT+08:00 2017
	 */
	public String getFile() {
		return file;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column email_info.file
	 * @param file  the value for email_info.file
	 * @mbggenerated  Mon Feb 27 09:16:07 GMT+08:00 2017
	 */
	public void setFile(String file) {
		this.file = file;
	}
}