package com.unbank.mybatis.entity;

import java.util.ArrayList;
import java.util.List;

public class EmailJobExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public EmailJobExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andJobNameIsNull() {
			addCriterion("job_name is null");
			return (Criteria) this;
		}

		public Criteria andJobNameIsNotNull() {
			addCriterion("job_name is not null");
			return (Criteria) this;
		}

		public Criteria andJobNameEqualTo(String value) {
			addCriterion("job_name =", value, "jobName");
			return (Criteria) this;
		}

		public Criteria andJobNameNotEqualTo(String value) {
			addCriterion("job_name <>", value, "jobName");
			return (Criteria) this;
		}

		public Criteria andJobNameGreaterThan(String value) {
			addCriterion("job_name >", value, "jobName");
			return (Criteria) this;
		}

		public Criteria andJobNameGreaterThanOrEqualTo(String value) {
			addCriterion("job_name >=", value, "jobName");
			return (Criteria) this;
		}

		public Criteria andJobNameLessThan(String value) {
			addCriterion("job_name <", value, "jobName");
			return (Criteria) this;
		}

		public Criteria andJobNameLessThanOrEqualTo(String value) {
			addCriterion("job_name <=", value, "jobName");
			return (Criteria) this;
		}

		public Criteria andJobNameLike(String value) {
			addCriterion("job_name like", value, "jobName");
			return (Criteria) this;
		}

		public Criteria andJobNameNotLike(String value) {
			addCriterion("job_name not like", value, "jobName");
			return (Criteria) this;
		}

		public Criteria andJobNameIn(List<String> values) {
			addCriterion("job_name in", values, "jobName");
			return (Criteria) this;
		}

		public Criteria andJobNameNotIn(List<String> values) {
			addCriterion("job_name not in", values, "jobName");
			return (Criteria) this;
		}

		public Criteria andJobNameBetween(String value1, String value2) {
			addCriterion("job_name between", value1, value2, "jobName");
			return (Criteria) this;
		}

		public Criteria andJobNameNotBetween(String value1, String value2) {
			addCriterion("job_name not between", value1, value2, "jobName");
			return (Criteria) this;
		}

		public Criteria andJobRuleIsNull() {
			addCriterion("job_rule is null");
			return (Criteria) this;
		}

		public Criteria andJobRuleIsNotNull() {
			addCriterion("job_rule is not null");
			return (Criteria) this;
		}

		public Criteria andJobRuleEqualTo(String value) {
			addCriterion("job_rule =", value, "jobRule");
			return (Criteria) this;
		}

		public Criteria andJobRuleNotEqualTo(String value) {
			addCriterion("job_rule <>", value, "jobRule");
			return (Criteria) this;
		}

		public Criteria andJobRuleGreaterThan(String value) {
			addCriterion("job_rule >", value, "jobRule");
			return (Criteria) this;
		}

		public Criteria andJobRuleGreaterThanOrEqualTo(String value) {
			addCriterion("job_rule >=", value, "jobRule");
			return (Criteria) this;
		}

		public Criteria andJobRuleLessThan(String value) {
			addCriterion("job_rule <", value, "jobRule");
			return (Criteria) this;
		}

		public Criteria andJobRuleLessThanOrEqualTo(String value) {
			addCriterion("job_rule <=", value, "jobRule");
			return (Criteria) this;
		}

		public Criteria andJobRuleLike(String value) {
			addCriterion("job_rule like", value, "jobRule");
			return (Criteria) this;
		}

		public Criteria andJobRuleNotLike(String value) {
			addCriterion("job_rule not like", value, "jobRule");
			return (Criteria) this;
		}

		public Criteria andJobRuleIn(List<String> values) {
			addCriterion("job_rule in", values, "jobRule");
			return (Criteria) this;
		}

		public Criteria andJobRuleNotIn(List<String> values) {
			addCriterion("job_rule not in", values, "jobRule");
			return (Criteria) this;
		}

		public Criteria andJobRuleBetween(String value1, String value2) {
			addCriterion("job_rule between", value1, value2, "jobRule");
			return (Criteria) this;
		}

		public Criteria andJobRuleNotBetween(String value1, String value2) {
			addCriterion("job_rule not between", value1, value2, "jobRule");
			return (Criteria) this;
		}

		public Criteria andEndIsNull() {
			addCriterion("end is null");
			return (Criteria) this;
		}

		public Criteria andEndIsNotNull() {
			addCriterion("end is not null");
			return (Criteria) this;
		}

		public Criteria andEndEqualTo(Integer value) {
			addCriterion("end =", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndNotEqualTo(Integer value) {
			addCriterion("end <>", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndGreaterThan(Integer value) {
			addCriterion("end >", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndGreaterThanOrEqualTo(Integer value) {
			addCriterion("end >=", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndLessThan(Integer value) {
			addCriterion("end <", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndLessThanOrEqualTo(Integer value) {
			addCriterion("end <=", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndIn(List<Integer> values) {
			addCriterion("end in", values, "end");
			return (Criteria) this;
		}

		public Criteria andEndNotIn(List<Integer> values) {
			addCriterion("end not in", values, "end");
			return (Criteria) this;
		}

		public Criteria andEndBetween(Integer value1, Integer value2) {
			addCriterion("end between", value1, value2, "end");
			return (Criteria) this;
		}

		public Criteria andEndNotBetween(Integer value1, Integer value2) {
			addCriterion("end not between", value1, value2, "end");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 01 15:57:53 GMT+08:00 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}