package com.unbank.mybatis.entity;

import java.util.Date;

public class EmailLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column email_log.id
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column email_log.sendemail
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private String sendemail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column email_log.cusemail
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private String cusemail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column email_log.time
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column email_log.contentid
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private Integer contentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column email_log.sendcode
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private Integer sendcode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column email_log.id
	 * @return  the value of email_log.id
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column email_log.id
	 * @param id  the value for email_log.id
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column email_log.sendemail
	 * @return  the value of email_log.sendemail
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public String getSendemail() {
		return sendemail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column email_log.sendemail
	 * @param sendemail  the value for email_log.sendemail
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setSendemail(String sendemail) {
		this.sendemail = sendemail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column email_log.cusemail
	 * @return  the value of email_log.cusemail
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public String getCusemail() {
		return cusemail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column email_log.cusemail
	 * @param cusemail  the value for email_log.cusemail
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setCusemail(String cusemail) {
		this.cusemail = cusemail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column email_log.time
	 * @return  the value of email_log.time
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column email_log.time
	 * @param time  the value for email_log.time
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column email_log.contentid
	 * @return  the value of email_log.contentid
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public Integer getContentid() {
		return contentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column email_log.contentid
	 * @param contentid  the value for email_log.contentid
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setContentid(Integer contentid) {
		this.contentid = contentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column email_log.sendcode
	 * @return  the value of email_log.sendcode
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public Integer getSendcode() {
		return sendcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column email_log.sendcode
	 * @param sendcode  the value for email_log.sendcode
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setSendcode(Integer sendcode) {
		this.sendcode = sendcode;
	}
}