package com.unbank.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EmailLogExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public EmailLogExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andSendemailIsNull() {
			addCriterion("sendemail is null");
			return (Criteria) this;
		}

		public Criteria andSendemailIsNotNull() {
			addCriterion("sendemail is not null");
			return (Criteria) this;
		}

		public Criteria andSendemailEqualTo(String value) {
			addCriterion("sendemail =", value, "sendemail");
			return (Criteria) this;
		}

		public Criteria andSendemailNotEqualTo(String value) {
			addCriterion("sendemail <>", value, "sendemail");
			return (Criteria) this;
		}

		public Criteria andSendemailGreaterThan(String value) {
			addCriterion("sendemail >", value, "sendemail");
			return (Criteria) this;
		}

		public Criteria andSendemailGreaterThanOrEqualTo(String value) {
			addCriterion("sendemail >=", value, "sendemail");
			return (Criteria) this;
		}

		public Criteria andSendemailLessThan(String value) {
			addCriterion("sendemail <", value, "sendemail");
			return (Criteria) this;
		}

		public Criteria andSendemailLessThanOrEqualTo(String value) {
			addCriterion("sendemail <=", value, "sendemail");
			return (Criteria) this;
		}

		public Criteria andSendemailLike(String value) {
			addCriterion("sendemail like", value, "sendemail");
			return (Criteria) this;
		}

		public Criteria andSendemailNotLike(String value) {
			addCriterion("sendemail not like", value, "sendemail");
			return (Criteria) this;
		}

		public Criteria andSendemailIn(List<String> values) {
			addCriterion("sendemail in", values, "sendemail");
			return (Criteria) this;
		}

		public Criteria andSendemailNotIn(List<String> values) {
			addCriterion("sendemail not in", values, "sendemail");
			return (Criteria) this;
		}

		public Criteria andSendemailBetween(String value1, String value2) {
			addCriterion("sendemail between", value1, value2, "sendemail");
			return (Criteria) this;
		}

		public Criteria andSendemailNotBetween(String value1, String value2) {
			addCriterion("sendemail not between", value1, value2, "sendemail");
			return (Criteria) this;
		}

		public Criteria andCusemailIsNull() {
			addCriterion("cusemail is null");
			return (Criteria) this;
		}

		public Criteria andCusemailIsNotNull() {
			addCriterion("cusemail is not null");
			return (Criteria) this;
		}

		public Criteria andCusemailEqualTo(String value) {
			addCriterion("cusemail =", value, "cusemail");
			return (Criteria) this;
		}

		public Criteria andCusemailNotEqualTo(String value) {
			addCriterion("cusemail <>", value, "cusemail");
			return (Criteria) this;
		}

		public Criteria andCusemailGreaterThan(String value) {
			addCriterion("cusemail >", value, "cusemail");
			return (Criteria) this;
		}

		public Criteria andCusemailGreaterThanOrEqualTo(String value) {
			addCriterion("cusemail >=", value, "cusemail");
			return (Criteria) this;
		}

		public Criteria andCusemailLessThan(String value) {
			addCriterion("cusemail <", value, "cusemail");
			return (Criteria) this;
		}

		public Criteria andCusemailLessThanOrEqualTo(String value) {
			addCriterion("cusemail <=", value, "cusemail");
			return (Criteria) this;
		}

		public Criteria andCusemailLike(String value) {
			addCriterion("cusemail like", value, "cusemail");
			return (Criteria) this;
		}

		public Criteria andCusemailNotLike(String value) {
			addCriterion("cusemail not like", value, "cusemail");
			return (Criteria) this;
		}

		public Criteria andCusemailIn(List<String> values) {
			addCriterion("cusemail in", values, "cusemail");
			return (Criteria) this;
		}

		public Criteria andCusemailNotIn(List<String> values) {
			addCriterion("cusemail not in", values, "cusemail");
			return (Criteria) this;
		}

		public Criteria andCusemailBetween(String value1, String value2) {
			addCriterion("cusemail between", value1, value2, "cusemail");
			return (Criteria) this;
		}

		public Criteria andCusemailNotBetween(String value1, String value2) {
			addCriterion("cusemail not between", value1, value2, "cusemail");
			return (Criteria) this;
		}

		public Criteria andTimeIsNull() {
			addCriterion("time is null");
			return (Criteria) this;
		}

		public Criteria andTimeIsNotNull() {
			addCriterion("time is not null");
			return (Criteria) this;
		}

		public Criteria andTimeEqualTo(Date value) {
			addCriterion("time =", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotEqualTo(Date value) {
			addCriterion("time <>", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThan(Date value) {
			addCriterion("time >", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("time >=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThan(Date value) {
			addCriterion("time <", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThanOrEqualTo(Date value) {
			addCriterion("time <=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeIn(List<Date> values) {
			addCriterion("time in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotIn(List<Date> values) {
			addCriterion("time not in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeBetween(Date value1, Date value2) {
			addCriterion("time between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotBetween(Date value1, Date value2) {
			addCriterion("time not between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andContentidIsNull() {
			addCriterion("contentid is null");
			return (Criteria) this;
		}

		public Criteria andContentidIsNotNull() {
			addCriterion("contentid is not null");
			return (Criteria) this;
		}

		public Criteria andContentidEqualTo(Integer value) {
			addCriterion("contentid =", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidNotEqualTo(Integer value) {
			addCriterion("contentid <>", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidGreaterThan(Integer value) {
			addCriterion("contentid >", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidGreaterThanOrEqualTo(Integer value) {
			addCriterion("contentid >=", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidLessThan(Integer value) {
			addCriterion("contentid <", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidLessThanOrEqualTo(Integer value) {
			addCriterion("contentid <=", value, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidIn(List<Integer> values) {
			addCriterion("contentid in", values, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidNotIn(List<Integer> values) {
			addCriterion("contentid not in", values, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidBetween(Integer value1, Integer value2) {
			addCriterion("contentid between", value1, value2, "contentid");
			return (Criteria) this;
		}

		public Criteria andContentidNotBetween(Integer value1, Integer value2) {
			addCriterion("contentid not between", value1, value2, "contentid");
			return (Criteria) this;
		}

		public Criteria andSendcodeIsNull() {
			addCriterion("sendcode is null");
			return (Criteria) this;
		}

		public Criteria andSendcodeIsNotNull() {
			addCriterion("sendcode is not null");
			return (Criteria) this;
		}

		public Criteria andSendcodeEqualTo(Integer value) {
			addCriterion("sendcode =", value, "sendcode");
			return (Criteria) this;
		}

		public Criteria andSendcodeNotEqualTo(Integer value) {
			addCriterion("sendcode <>", value, "sendcode");
			return (Criteria) this;
		}

		public Criteria andSendcodeGreaterThan(Integer value) {
			addCriterion("sendcode >", value, "sendcode");
			return (Criteria) this;
		}

		public Criteria andSendcodeGreaterThanOrEqualTo(Integer value) {
			addCriterion("sendcode >=", value, "sendcode");
			return (Criteria) this;
		}

		public Criteria andSendcodeLessThan(Integer value) {
			addCriterion("sendcode <", value, "sendcode");
			return (Criteria) this;
		}

		public Criteria andSendcodeLessThanOrEqualTo(Integer value) {
			addCriterion("sendcode <=", value, "sendcode");
			return (Criteria) this;
		}

		public Criteria andSendcodeIn(List<Integer> values) {
			addCriterion("sendcode in", values, "sendcode");
			return (Criteria) this;
		}

		public Criteria andSendcodeNotIn(List<Integer> values) {
			addCriterion("sendcode not in", values, "sendcode");
			return (Criteria) this;
		}

		public Criteria andSendcodeBetween(Integer value1, Integer value2) {
			addCriterion("sendcode between", value1, value2, "sendcode");
			return (Criteria) this;
		}

		public Criteria andSendcodeNotBetween(Integer value1, Integer value2) {
			addCriterion("sendcode not between", value1, value2, "sendcode");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table email_log
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 22 14:28:43 GMT+08:00 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}