package com.unbank.mybatis.entity;

public class EmailJob {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column job.id
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column job.job_name
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private String jobName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column job.job_rule
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private String jobRule;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column job.end
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private Integer end;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column job.id
	 * @return  the value of job.id
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column job.id
	 * @param id  the value for job.id
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column job.job_name
	 * @return  the value of job.job_name
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public String getJobName() {
		return jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column job.job_name
	 * @param jobName  the value for job.job_name
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column job.job_rule
	 * @return  the value of job.job_rule
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public String getJobRule() {
		return jobRule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column job.job_rule
	 * @param jobRule  the value for job.job_rule
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setJobRule(String jobRule) {
		this.jobRule = jobRule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column job.end
	 * @return  the value of job.end
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public Integer getEnd() {
		return end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column job.end
	 * @param end  the value for job.end
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setEnd(Integer end) {
		this.end = end;
	}
}