package com.unbank.mybatis.entity;

public class EmailInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column email_info.id
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column email_info.title
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column email_info.content
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column email_info.id
	 * @return  the value of email_info.id
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column email_info.id
	 * @param id  the value for email_info.id
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column email_info.title
	 * @return  the value of email_info.title
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column email_info.title
	 * @param title  the value for email_info.title
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column email_info.content
	 * @return  the value of email_info.content
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column email_info.content
	 * @param content  the value for email_info.content
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}
}