package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.EmailReiver;
import com.unbank.mybatis.entity.EmailReiverExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmailReiverMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reiver_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int countByExample(EmailReiverExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reiver_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int deleteByExample(EmailReiverExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reiver_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reiver_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int insert(EmailReiver record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reiver_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int insertSelective(EmailReiver record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reiver_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	List<EmailReiver> selectByExample(EmailReiverExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reiver_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	EmailReiver selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reiver_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") EmailReiver record, @Param("example") EmailReiverExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reiver_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") EmailReiver record, @Param("example") EmailReiverExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reiver_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(EmailReiver record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reiver_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByPrimaryKey(EmailReiver record);
}