package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.EmailLog;
import com.unbank.mybatis.entity.EmailLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmailLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int countByExample(EmailLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int deleteByExample(EmailLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int insert(EmailLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int insertSelective(EmailLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	List<EmailLog> selectByExample(EmailLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	EmailLog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") EmailLog record, @Param("example") EmailLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") EmailLog record, @Param("example") EmailLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(EmailLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_log
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByPrimaryKey(EmailLog record);
}