package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.EmailSender;
import com.unbank.mybatis.entity.EmailSenderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmailSenderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sender_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int countByExample(EmailSenderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sender_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int deleteByExample(EmailSenderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sender_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sender_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int insert(EmailSender record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sender_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int insertSelective(EmailSender record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sender_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	List<EmailSender> selectByExample(EmailSenderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sender_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	EmailSender selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sender_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") EmailSender record, @Param("example") EmailSenderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sender_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") EmailSender record, @Param("example") EmailSenderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sender_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(EmailSender record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sender_email
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByPrimaryKey(EmailSender record);
}