package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.EmailJob;
import com.unbank.mybatis.entity.EmailJobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmailJobMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int countByExample(EmailJobExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int deleteByExample(EmailJobExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int insert(EmailJob record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int insertSelective(EmailJob record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	List<EmailJob> selectByExample(EmailJobExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	EmailJob selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") EmailJob record, @Param("example") EmailJobExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") EmailJob record, @Param("example") EmailJobExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(EmailJob record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table job
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByPrimaryKey(EmailJob record);
}