package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.EmailInfo;
import com.unbank.mybatis.entity.EmailInfoExample;
import com.unbank.mybatis.entity.EmailInfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmailInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_info
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int countByExample(EmailInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_info
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int deleteByExample(EmailInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_info
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_info
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int insert(EmailInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_info
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int insertSelective(EmailInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_info
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	List<EmailInfo> selectByExampleWithBLOBs(EmailInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_info
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	List<EmailInfo> selectByExample(EmailInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_info
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	EmailInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_info
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByExampleSelective(@Param("record") EmailInfo record, @Param("example") EmailInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_info
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") EmailInfo record, @Param("example") EmailInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_info
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByExample(@Param("record") EmailInfo record, @Param("example") EmailInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_info
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(EmailInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_info
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByPrimaryKeyWithBLOBs(EmailInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table email_info
	 * @mbggenerated  Wed Mar 01 16:14:44 GMT+08:00 2017
	 */
	int updateByPrimaryKey(EmailInfo record);
}